FROM node:22.16.0-alpine

# Instalar pnpm y Nest CLI globalmente
RUN npm install -g pnpm @nestjs/cli

WORKDIR /usr/src/app

# Copiar archivos de dependencias
COPY package.json pnpm-lock.yaml ./

# Configurar el store de pnpm dentro del contenedor
RUN pnpm config set store-dir /usr/src/app/.pnpm-store

# Instalar dependencias del proyecto
RUN pnpm install

# Copiar el resto de la aplicación
COPY . .

EXPOSE 3000

# Comando para desarrollo con hot reload
CMD ["pnpm", "run", "start:dev"]